interface Anomaly {
    id: number;
    date: string;
    number_of_anomalies: number;
    camera_id: string;
    area: string;
    max_attendance: number;
    warning: string;
    duration: number;
  }

export const anomalyData: Anomaly[] = [
  {
    id: 1,
    date: '29/02/2024',
    number_of_anomalies: 78,
    camera_id: 'CAM10-1',
    area: 'playground',
    max_attendance: 5,
    warning: 'no weapon',
    duration: 6,
  },
  {
    id: 2,
    date: '04/07/2024',
    number_of_anomalies: 45,
    camera_id: 'CAM08-1',
    area: 'classroom',
    max_attendance: 1,
    warning: 'have weapon',
    duration: 16,
  },
  {
    id: 3,
    date: '17/03/2024',
    number_of_anomalies: 70,
    camera_id: 'CAM10-2',
    area: 'gymnasium',
    max_attendance: 3,
    warning: 'have weapon',
    duration: 20,
  },
  {
    id: 4,
    date: '19/10/2023',
    number_of_anomalies: 69,
    camera_id: 'CAM10-3',
    area: 'gymnasium',
    max_attendance: 1,
    warning: 'no weapon',
    duration: 15,
  },
  {
    id: 5,
    date: '03/10/2023',
    number_of_anomalies: 48,
    camera_id: 'CAM10-2',
    area: 'classroom',
    max_attendance: 3,
    warning: 'no weapon',
    duration: 7,
  },
  {
    id: 6,
    date: '03/11/2023',
    number_of_anomalies: 74,
    camera_id: 'CAM10-2',
    area: 'playground',
    max_attendance: 4,
    warning: 'no weapon',
    duration: 12,
  },
  {
    id: 7,
    date: '02/07/2024',
    number_of_anomalies: 81,
    camera_id: 'CAM05-5',
    area: 'classroom',
    max_attendance: 8,
    warning: 'no weapon',
    duration: 19,
  },
  {
    id: 8,
    date: '16/01/2024',
    number_of_anomalies: 14,
    camera_id: 'CAM02-6',
    area: 'gymnasium',
    max_attendance: 2,
    warning: 'no weapon',
    duration: 11,
  },
  {
    id: 9,
    date: '10/04/2024',
    number_of_anomalies: 62,
    camera_id: 'CAM01-3',
    area: 'gymnasium',
    max_attendance: 1,
    warning: 'no weapon',
    duration: 8,
  },
  {
    id: 10,
    date: '17/11/2023',
    number_of_anomalies: 39,
    camera_id: 'CAM10-2',
    area: 'cafeteria',
    max_attendance: 4,
    warning: 'no weapon',
    duration: 6,
  },
  {
    id: 11,
    date: '20/02/2024',
    number_of_anomalies: 6,
    camera_id: 'CAM10-3',
    area: 'cafeteria',
    max_attendance: 8,
    warning: 'have weapon',
    duration: 14,
  },
  {
    id: 12,
    date: '17/01/2024',
    number_of_anomalies: 59,
    camera_id: 'CAM10-9',
    area: 'playground',
    max_attendance: 3,
    warning: 'have weapon',
    duration: 20,
  },
  {
    id: 13,
    date: '03/12/2023',
    number_of_anomalies: 44,
    camera_id: 'CAM02-5',
    area: 'playground',
    max_attendance: 7,
    warning: 'have weapon',
    duration: 17,
  },
  {
    id: 14,
    date: '04/06/2024',
    number_of_anomalies: 4,
    camera_id: 'CAM10-3',
    area: 'playground',
    max_attendance: 3,
    warning: 'have weapon',
    duration: 13,
  },
  {
    id: 15,
    date: '04/04/2024',
    number_of_anomalies: 19,
    camera_id: 'CAM10-5',
    area: 'classroom',
    max_attendance: 4,
    warning: 'no weapon',
    duration: 7,
  },
  {
    id: 16,
    date: '29/11/2023',
    number_of_anomalies: 86,
    camera_id: 'CAM10-8',
    area: 'library',
    max_attendance: 1,
    warning: 'no weapon',
    duration: 20,
  },
  {
    id: 17,
    date: '28/10/2023',
    number_of_anomalies: 71,
    camera_id: 'CAM01-5',
    area: 'library',
    max_attendance: 3,
    warning: 'have weapon',
    duration: 3,
  },
  {
    id: 18,
    date: '06/12/2023',
    number_of_anomalies: 43,
    camera_id: 'CAM01-5',
    area: 'gymnasium',
    max_attendance: 6,
    warning: 'have weapon',
    duration: 7,
  },
  {
    id: 19,
    date: '28/06/2024',
    number_of_anomalies: 34,
    camera_id: 'CAM10-9',
    area: 'playground',
    max_attendance: 7,
    warning: 'have weapon',
    duration: 3,
  },
  {
    id: 20,
    date: '09/11/2023',
    number_of_anomalies: 32,
    camera_id: 'CAM05-6',
    area: 'library',
    max_attendance: 3,
    warning: 'no weapon',
    duration: 6,
  },
  {
    id: 21,
    date: '14/11/2023',
    number_of_anomalies: 72,
    camera_id: 'CAM10-8',
    area: 'cafeteria',
    max_attendance: 8,
    warning: 'no weapon',
    duration: 9,
  },
  {
    id: 22,
    date: '14/07/2024',
    number_of_anomalies: 68,
    camera_id: 'CAM10-9',
    area: 'cafeteria',
    max_attendance: 1,
    warning: 'have weapon',
    duration: 14,
  },
  {
    id: 23,
    date: '14/08/2024',
    number_of_anomalies: 73,
    camera_id: 'CAM03-4',
    area: 'cafeteria',
    max_attendance: 3,
    warning: 'have weapon',
    duration: 18,
  },
  {
    id: 24,
    date: '10/01/2024',
    number_of_anomalies: 58,
    camera_id: 'CAM10-8',
    area: 'playground',
    max_attendance: 8,
    warning: 'have weapon',
    duration: 15,
  },
  {
    id: 25,
    date: '30/11/2023',
    number_of_anomalies: 26,
    camera_id: 'CAM10-5',
    area: 'classroom',
    max_attendance: 2,
    warning: 'no weapon',
    duration: 16,
  },
  {
    id: 26,
    date: '30/04/2024',
    number_of_anomalies: 62,
    camera_id: 'CAM05-3',
    area: 'gymnasium',
    max_attendance: 1,
    warning: 'no weapon',
    duration: 4,
  },
  {
    id: 27,
    date: '19/01/2024',
    number_of_anomalies: 84,
    camera_id: 'CAM02-2',
    area: 'library',
    max_attendance: 7,
    warning: 'no weapon',
    duration: 7,
  },
  {
    id: 28,
    date: '25/11/2023',
    number_of_anomalies: 10,
    camera_id: 'CAM05-7',
    area: 'cafeteria',
    max_attendance: 4,
    warning: 'have weapon',
    duration: 10,
  },
  {
    id: 29,
    date: '06/10/2023',
    number_of_anomalies: 52,
    camera_id: 'CAM01-4',
    area: 'library',
    max_attendance: 8,
    warning: 'no weapon',
    duration: 6,
  },
  {
    id: 30,
    date: '09/11/2023',
    number_of_anomalies: 65,
    camera_id: 'CAM02-9',
    area: 'gymnasium',
    max_attendance: 7,
    warning: 'no weapon',
    duration: 14,
  },
  {
    id: 31,
    date: '04/02/2024',
    number_of_anomalies: 63,
    camera_id: 'CAM10-1',
    area: 'gymnasium',
    max_attendance: 1,
    warning: 'no weapon',
    duration: 17,
  },
  {
    id: 32,
    date: '14/10/2023',
    number_of_anomalies: 53,
    camera_id: 'CAM10-1',
    area: 'gymnasium',
    max_attendance: 2,
    warning: 'have weapon',
    duration: 7,
  },
  {
    id: 33,
    date: '10/07/2024',
    number_of_anomalies: 3,
    camera_id: 'CAM06-1',
    area: 'gymnasium',
    max_attendance: 1,
    warning: 'have weapon',
    duration: 18,
  },
  {
    id: 34,
    date: '30/05/2024',
    number_of_anomalies: 94,
    camera_id: 'CAM07-3',
    area: 'library',
    max_attendance: 8,
    warning: 'have weapon',
    duration: 8,
  },
  {
    id: 35,
    date: '23/09/2024',
    number_of_anomalies: 75,
    camera_id: 'CAM10-8',
    area: 'gymnasium',
    max_attendance: 3,
    warning: 'have weapon',
    duration: 18,
  },
  {
    id: 36,
    date: '05/01/2024',
    number_of_anomalies: 86,
    camera_id: 'CAM07-5',
    area: 'playground',
    max_attendance: 4,
    warning: 'have weapon',
    duration: 15,
  },
  {
    id: 37,
    date: '28/09/2023',
    number_of_anomalies: 89,
    camera_id: 'CAM02-4',
    area: 'library',
    max_attendance: 3,
    warning: 'no weapon',
    duration: 13,
  },
  {
    id: 38,
    date: '05/12/2023',
    number_of_anomalies: 60,
    camera_id: 'CAM10-2',
    area: 'playground',
    max_attendance: 2,
    warning: 'no weapon',
    duration: 15,
  },
  {
    id: 39,
    date: '20/07/2024',
    number_of_anomalies: 60,
    camera_id: 'CAM10-5',
    area: 'library',
    max_attendance: 2,
    warning: 'no weapon',
    duration: 4,
  },
  {
    id: 40,
    date: '29/10/2023',
    number_of_anomalies: 96,
    camera_id: 'CAM10-2',
    area: 'classroom',
    max_attendance: 2,
    warning: 'have weapon',
    duration: 16,
  },
  {
    id: 41,
    date: '06/11/2023',
    number_of_anomalies: 79,
    camera_id: 'CAM04-9',
    area: 'playground',
    max_attendance: 2,
    warning: 'no weapon',
    duration: 7,
  },
  {
    id: 42,
    date: '17/08/2024',
    number_of_anomalies: 21,
    camera_id: 'CAM05-6',
    area: 'playground',
    max_attendance: 3,
    warning: 'no weapon',
    duration: 12,
  },
  {
    id: 43,
    date: '21/07/2024',
    number_of_anomalies: 43,
    camera_id: 'CAM10-7',
    area: 'playground',
    max_attendance: 6,
    warning: 'no weapon',
    duration: 14,
  },
  {
    id: 44,
    date: '03/05/2024',
    number_of_anomalies: 27,
    camera_id: 'CAM10-3',
    area: 'classroom',
    max_attendance: 4,
    warning: 'no weapon',
    duration: 9,
  },
  {
    id: 45,
    date: '31/03/2024',
    number_of_anomalies: 83,
    camera_id: 'CAM10-9',
    area: 'library',
    max_attendance: 6,
    warning: 'have weapon',
    duration: 17,
  },
  {
    id: 46,
    date: '08/04/2024',
    number_of_anomalies: 52,
    camera_id: 'CAM03-6',
    area: 'playground',
    max_attendance: 7,
    warning: 'have weapon',
    duration: 18,
  },
  {
    id: 47,
    date: '11/12/2023',
    number_of_anomalies: 78,
    camera_id: 'CAM07-3',
    area: 'library',
    max_attendance: 2,
    warning: 'no weapon',
    duration: 13,
  },
  {
    id: 48,
    date: '22/06/2024',
    number_of_anomalies: 58,
    camera_id: 'CAM10-9',
    area: 'classroom',
    max_attendance: 8,
    warning: 'no weapon',
    duration: 5,
  },
  {
    id: 49,
    date: '11/10/2023',
    number_of_anomalies: 100,
    camera_id: 'CAM10-1',
    area: 'classroom',
    max_attendance: 7,
    warning: 'no weapon',
    duration: 19,
  },
  {
    id: 50,
    date: '11/03/2024',
    number_of_anomalies: 78,
    camera_id: 'CAM06-1',
    area: 'playground',
    max_attendance: 1,
    warning: 'no weapon',
    duration: 6,
  },
  {
    id: 51,
    date: '25/01/2024',
    number_of_anomalies: 29,
    camera_id: 'CAM08-5',
    area: 'cafeteria',
    max_attendance: 5,
    warning: 'no weapon',
    duration: 5,
  },
  {
    id: 52,
    date: '04/09/2024',
    number_of_anomalies: 64,
    camera_id: 'CAM10-9',
    area: 'gymnasium',
    max_attendance: 4,
    warning: 'have weapon',
    duration: 8,
  },
  {
    id: 53,
    date: '10/05/2024',
    number_of_anomalies: 89,
    camera_id: 'CAM01-7',
    area: 'cafeteria',
    max_attendance: 6,
    warning: 'have weapon',
    duration: 8,
  },
  {
    id: 54,
    date: '22/07/2024',
    number_of_anomalies: 43,
    camera_id: 'CAM03-5',
    area: 'classroom',
    max_attendance: 2,
    warning: 'have weapon',
    duration: 9,
  },
  {
    id: 55,
    date: '21/09/2024',
    number_of_anomalies: 61,
    camera_id: 'CAM04-2',
    area: 'library',
    max_attendance: 6,
    warning: 'no weapon',
    duration: 5,
  },
  {
    id: 56,
    date: '17/07/2024',
    number_of_anomalies: 72,
    camera_id: 'CAM02-9',
    area: 'playground',
    max_attendance: 4,
    warning: 'have weapon',
    duration: 20,
  },
  {
    id: 57,
    date: '14/06/2024',
    number_of_anomalies: 62,
    camera_id: 'CAM06-6',
    area: 'gymnasium',
    max_attendance: 1,
    warning: 'have weapon',
    duration: 9,
  },
  {
    id: 58,
    date: '24/05/2024',
    number_of_anomalies: 74,
    camera_id: 'CAM10-3',
    area: 'cafeteria',
    max_attendance: 2,
    warning: 'no weapon',
    duration: 10,
  },
  {
    id: 59,
    date: '21/06/2024',
    number_of_anomalies: 93,
    camera_id: 'CAM05-7',
    area: 'cafeteria',
    max_attendance: 1,
    warning: 'no weapon',
    duration: 17,
  },
  {
    id: 60,
    date: '27/10/2023',
    number_of_anomalies: 34,
    camera_id: 'CAM10-8',
    area: 'playground',
    max_attendance: 2,
    warning: 'have weapon',
    duration: 4,
  },
  {
    id: 61,
    date: '27/07/2024',
    number_of_anomalies: 45,
    camera_id: 'CAM10-4',
    area: 'playground',
    max_attendance: 4,
    warning: 'no weapon',
    duration: 4,
  },
  {
    id: 62,
    date: '28/04/2024',
    number_of_anomalies: 93,
    camera_id: 'CAM10-2',
    area: 'classroom',
    max_attendance: 6,
    warning: 'have weapon',
    duration: 8,
  },
  {
    id: 63,
    date: '04/10/2023',
    number_of_anomalies: 31,
    camera_id: 'CAM05-3',
    area: 'gymnasium',
    max_attendance: 5,
    warning: 'no weapon',
    duration: 7,
  },
  {
    id: 64,
    date: '19/07/2024',
    number_of_anomalies: 84,
    camera_id: 'CAM10-8',
    area: 'cafeteria',
    max_attendance: 5,
    warning: 'have weapon',
    duration: 14,
  },
  {
    id: 65,
    date: '20/01/2024',
    number_of_anomalies: 13,
    camera_id: 'CAM10-2',
    area: 'playground',
    max_attendance: 5,
    warning: 'no weapon',
    duration: 5,
  },
  {
    id: 66,
    date: '20/05/2024',
    number_of_anomalies: 72,
    camera_id: 'CAM10-7',
    area: 'gymnasium',
    max_attendance: 5,
    warning: 'no weapon',
    duration: 3,
  },
  {
    id: 67,
    date: '10/12/2023',
    number_of_anomalies: 68,
    camera_id: 'CAM10-9',
    area: 'cafeteria',
    max_attendance: 4,
    warning: 'no weapon',
    duration: 7,
  },
  {
    id: 68,
    date: '27/01/2024',
    number_of_anomalies: 80,
    camera_id: 'CAM10-7',
    area: 'playground',
    max_attendance: 4,
    warning: 'no weapon',
    duration: 9,
  },
  {
    id: 69,
    date: '26/02/2024',
    number_of_anomalies: 8,
    camera_id: 'CAM10-5',
    area: 'gymnasium',
    max_attendance: 3,
    warning: 'have weapon',
    duration: 14,
  },
  {
    id: 70,
    date: '28/08/2024',
    number_of_anomalies: 16,
    camera_id: 'CAM10-7',
    area: 'gymnasium',
    max_attendance: 2,
    warning: 'no weapon',
    duration: 6,
  },
  {
    id: 71,
    date: '19/04/2024',
    number_of_anomalies: 48,
    camera_id: 'CAM05-4',
    area: 'gymnasium',
    max_attendance: 7,
    warning: 'no weapon',
    duration: 6,
  },
  {
    id: 72,
    date: '10/12/2023',
    number_of_anomalies: 44,
    camera_id: 'CAM10-4',
    area: 'gymnasium',
    max_attendance: 6,
    warning: 'have weapon',
    duration: 7,
  },
  {
    id: 73,
    date: '29/02/2024',
    number_of_anomalies: 54,
    camera_id: 'CAM08-5',
    area: 'classroom',
    max_attendance: 3,
    warning: 'have weapon',
    duration: 18,
  },
  {
    id: 74,
    date: '01/10/2023',
    number_of_anomalies: 46,
    camera_id: 'CAM10-6',
    area: 'playground',
    max_attendance: 3,
    warning: 'have weapon',
    duration: 20,
  },
  {
    id: 75,
    date: '11/04/2024',
    number_of_anomalies: 27,
    camera_id: 'CAM10-8',
    area: 'library',
    max_attendance: 8,
    warning: 'have weapon',
    duration: 20,
  },
  {
    id: 76,
    date: '10/08/2024',
    number_of_anomalies: 36,
    camera_id: 'CAM10-5',
    area: 'cafeteria',
    max_attendance: 8,
    warning: 'have weapon',
    duration: 15,
  },
  {
    id: 77,
    date: '31/10/2023',
    number_of_anomalies: 34,
    camera_id: 'CAM09-5',
    area: 'cafeteria',
    max_attendance: 4,
    warning: 'have weapon',
    duration: 14,
  },
  {
    id: 78,
    date: '23/10/2023',
    number_of_anomalies: 29,
    camera_id: 'CAM10-9',
    area: 'playground',
    max_attendance: 4,
    warning: 'no weapon',
    duration: 6,
  },
  {
    id: 79,
    date: '25/04/2024',
    number_of_anomalies: 74,
    camera_id: 'CAM06-8',
    area: 'library',
    max_attendance: 8,
    warning: 'have weapon',
    duration: 17,
  },
  {
    id: 80,
    date: '05/07/2024',
    number_of_anomalies: 77,
    camera_id: 'CAM04-1',
    area: 'classroom',
    max_attendance: 6,
    warning: 'have weapon',
    duration: 17,
  },
  {
    id: 81,
    date: '10/09/2024',
    number_of_anomalies: 66,
    camera_id: 'CAM10-8',
    area: 'playground',
    max_attendance: 6,
    warning: 'no weapon',
    duration: 14,
  },
  {
    id: 82,
    date: '06/02/2024',
    number_of_anomalies: 43,
    camera_id: 'CAM10-3',
    area: 'library',
    max_attendance: 5,
    warning: 'have weapon',
    duration: 6,
  },
  {
    id: 83,
    date: '28/09/2023',
    number_of_anomalies: 28,
    camera_id: 'CAM08-6',
    area: 'classroom',
    max_attendance: 4,
    warning: 'no weapon',
    duration: 15,
  },
  {
    id: 84,
    date: '03/06/2024',
    number_of_anomalies: 42,
    camera_id: 'CAM05-6',
    area: 'cafeteria',
    max_attendance: 6,
    warning: 'have weapon',
    duration: 14,
  },
  {
    id: 85,
    date: '18/03/2024',
    number_of_anomalies: 10,
    camera_id: 'CAM06-1',
    area: 'cafeteria',
    max_attendance: 8,
    warning: 'no weapon',
    duration: 13,
  },
  {
    id: 86,
    date: '07/11/2023',
    number_of_anomalies: 82,
    camera_id: 'CAM06-3',
    area: 'library',
    max_attendance: 5,
    warning: 'no weapon',
    duration: 9,
  },
  {
    id: 87,
    date: '17/12/2023',
    number_of_anomalies: 38,
    camera_id: 'CAM10-9',
    area: 'library',
    max_attendance: 3,
    warning: 'no weapon',
    duration: 13,
  },
  {
    id: 88,
    date: '04/12/2023',
    number_of_anomalies: 96,
    camera_id: 'CAM10-6',
    area: 'cafeteria',
    max_attendance: 7,
    warning: 'have weapon',
    duration: 13,
  },
  {
    id: 89,
    date: '22/12/2023',
    number_of_anomalies: 19,
    camera_id: 'CAM10-7',
    area: 'classroom',
    max_attendance: 1,
    warning: 'have weapon',
    duration: 7,
  },
  {
    id: 90,
    date: '07/12/2023',
    number_of_anomalies: 99,
    camera_id: 'CAM10-1',
    area: 'library',
    max_attendance: 3,
    warning: 'no weapon',
    duration: 18,
  },
  {
    id: 91,
    date: '17/03/2024',
    number_of_anomalies: 11,
    camera_id: 'CAM10-1',
    area: 'gymnasium',
    max_attendance: 7,
    warning: 'no weapon',
    duration: 12,
  },
  {
    id: 92,
    date: '05/08/2024',
    number_of_anomalies: 46,
    camera_id: 'CAM07-8',
    area: 'playground',
    max_attendance: 4,
    warning: 'have weapon',
    duration: 12,
  },
  {
    id: 93,
    date: '21/10/2023',
    number_of_anomalies: 31,
    camera_id: 'CAM03-8',
    area: 'cafeteria',
    max_attendance: 4,
    warning: 'no weapon',
    duration: 12,
  },
  {
    id: 94,
    date: '30/05/2024',
    number_of_anomalies: 27,
    camera_id: 'CAM01-9',
    area: 'library',
    max_attendance: 1,
    warning: 'have weapon',
    duration: 11,
  },
  {
    id: 95,
    date: '17/11/2023',
    number_of_anomalies: 96,
    camera_id: 'CAM04-6',
    area: 'playground',
    max_attendance: 2,
    warning: 'have weapon',
    duration: 19,
  },
  {
    id: 96,
    date: '11/11/2023',
    number_of_anomalies: 91,
    camera_id: 'CAM10-9',
    area: 'cafeteria',
    max_attendance: 8,
    warning: 'no weapon',
    duration: 12,
  },
  {
    id: 97,
    date: '29/01/2024',
    number_of_anomalies: 66,
    camera_id: 'CAM07-7',
    area: 'gymnasium',
    max_attendance: 5,
    warning: 'no weapon',
    duration: 9,
  },
  {
    id: 98,
    date: '10/10/2023',
    number_of_anomalies: 11,
    camera_id: 'CAM07-8',
    area: 'gymnasium',
    max_attendance: 5,
    warning: 'have weapon',
    duration: 20,
  },
  {
    id: 99,
    date: '15/03/2024',
    number_of_anomalies: 0,
    camera_id: 'CAM01-3',
    area: 'classroom',
    max_attendance: 2,
    warning: 'have weapon',
    duration: 15,
  },
  {
    id: 100,
    date: '21/04/2024',
    number_of_anomalies: 20,
    camera_id: 'CAM10-4',
    area: 'classroom',
    max_attendance: 2,
    warning: 'have weapon',
    duration: 4,
  },
]
