import { ChartConfig } from '../components/ui/chart'

export interface Anomaly {
  key: number
  date: string
  number_of_anomalies: number
  camera_id: string
  area: string
  max_attendance: number
  warning: boolean
  duration: number
}

export const chartConfig = {
  key: {
    label: 'ID',
    color: '#e11d48',
  },
  date: {
    label: 'Date',
    color: '#2563eb',
  },
  number_of_anomalies: {
    label: 'Num of Anomalies',
    color: '#dc2626',
  },
  camera_id: {
    label: 'Camera ID',
    color: '#facc15',
  },
  area: {
    label: 'Area',
    color: '#2563eb',
  },
  max_attendance: {
    label: 'Max Attendance',
    color: '#f97316',
  },
  warning: {
    label: 'Warning',
    color: '#facc15',
  },
  duration: {
    label: 'Duration',
    color: '#2563eb',
  },
} satisfies ChartConfig

export const anomalyData: Anomaly[] = [
  {
    key: 1,
    date: '29/02/2024',
    number_of_anomalies: 78,
    camera_id: 'CAM10-1',
    area: 'playground',
    max_attendance: 5,
    warning: false,
    duration: 6,
  },
  {
    key: 2,
    date: '04/07/2024',
    number_of_anomalies: 45,
    camera_id: 'CAM08-1',
    area: 'classroom',
    max_attendance: 1,
    warning: true,
    duration: 16,
  },
  {
    key: 3,
    date: '17/03/2024',
    number_of_anomalies: 70,
    camera_id: 'CAM10-2',
    area: 'gymnasium',
    max_attendance: 3,
    warning: true,
    duration: 20,
  },
  {
    key: 4,
    date: '19/10/2023',
    number_of_anomalies: 69,
    camera_id: 'CAM10-3',
    area: 'gymnasium',
    max_attendance: 1,
    warning: false,
    duration: 15,
  },
  {
    key: 5,
    date: '03/10/2023',
    number_of_anomalies: 48,
    camera_id: 'CAM10-2',
    area: 'classroom',
    max_attendance: 3,
    warning: false,
    duration: 7,
  },
  {
    key: 6,
    date: '03/11/2023',
    number_of_anomalies: 74,
    camera_id: 'CAM10-2',
    area: 'playground',
    max_attendance: 4,
    warning: false,
    duration: 12,
  },
  {
    key: 7,
    date: '02/07/2024',
    number_of_anomalies: 81,
    camera_id: 'CAM05-5',
    area: 'classroom',
    max_attendance: 8,
    warning: false,
    duration: 19,
  },
  {
    key: 8,
    date: '16/01/2024',
    number_of_anomalies: 14,
    camera_id: 'CAM02-6',
    area: 'gymnasium',
    max_attendance: 2,
    warning: false,
    duration: 11,
  },
  {
    key: 9,
    date: '10/04/2024',
    number_of_anomalies: 62,
    camera_id: 'CAM01-3',
    area: 'gymnasium',
    max_attendance: 1,
    warning: false,
    duration: 8,
  },
  {
    key: 10,
    date: '17/11/2023',
    number_of_anomalies: 39,
    camera_id: 'CAM10-2',
    area: 'cafeteria',
    max_attendance: 4,
    warning: false,
    duration: 6,
  },
  {
    key: 11,
    date: '20/02/2024',
    number_of_anomalies: 6,
    camera_id: 'CAM10-3',
    area: 'cafeteria',
    max_attendance: 8,
    warning: true,
    duration: 14,
  },
  {
    key: 12,
    date: '17/01/2024',
    number_of_anomalies: 59,
    camera_id: 'CAM10-9',
    area: 'playground',
    max_attendance: 3,
    warning: true,
    duration: 20,
  },
  {
    key: 13,
    date: '03/12/2023',
    number_of_anomalies: 44,
    camera_id: 'CAM02-5',
    area: 'playground',
    max_attendance: 7,
    warning: true,
    duration: 17,
  },
  {
    key: 14,
    date: '04/06/2024',
    number_of_anomalies: 4,
    camera_id: 'CAM10-3',
    area: 'playground',
    max_attendance: 3,
    warning: true,
    duration: 13,
  },
  {
    key: 15,
    date: '04/04/2024',
    number_of_anomalies: 19,
    camera_id: 'CAM10-5',
    area: 'classroom',
    max_attendance: 4,
    warning: false,
    duration: 7,
  },
  {
    key: 16,
    date: '29/11/2023',
    number_of_anomalies: 86,
    camera_id: 'CAM10-8',
    area: 'library',
    max_attendance: 1,
    warning: false,
    duration: 20,
  },
  {
    key: 17,
    date: '28/10/2023',
    number_of_anomalies: 71,
    camera_id: 'CAM01-5',
    area: 'library',
    max_attendance: 3,
    warning: true,
    duration: 3,
  },
  {
    key: 18,
    date: '06/12/2023',
    number_of_anomalies: 43,
    camera_id: 'CAM01-5',
    area: 'gymnasium',
    max_attendance: 6,
    warning: true,
    duration: 7,
  },
  {
    key: 19,
    date: '28/06/2024',
    number_of_anomalies: 34,
    camera_id: 'CAM10-9',
    area: 'playground',
    max_attendance: 7,
    warning: true,
    duration: 3,
  },
  {
    key: 20,
    date: '09/11/2023',
    number_of_anomalies: 32,
    camera_id: 'CAM05-6',
    area: 'library',
    max_attendance: 3,
    warning: false,
    duration: 6,
  },
  {
    key: 21,
    date: '14/11/2023',
    number_of_anomalies: 72,
    camera_id: 'CAM10-8',
    area: 'cafeteria',
    max_attendance: 8,
    warning: false,
    duration: 9,
  },
  {
    key: 22,
    date: '14/07/2024',
    number_of_anomalies: 68,
    camera_id: 'CAM10-9',
    area: 'cafeteria',
    max_attendance: 1,
    warning: true,
    duration: 14,
  },
  {
    key: 23,
    date: '14/08/2024',
    number_of_anomalies: 73,
    camera_id: 'CAM03-4',
    area: 'cafeteria',
    max_attendance: 3,
    warning: true,
    duration: 18,
  },
  {
    key: 24,
    date: '10/01/2024',
    number_of_anomalies: 58,
    camera_id: 'CAM10-8',
    area: 'playground',
    max_attendance: 8,
    warning: true,
    duration: 15,
  },
  {
    key: 25,
    date: '30/11/2023',
    number_of_anomalies: 26,
    camera_id: 'CAM10-5',
    area: 'classroom',
    max_attendance: 2,
    warning: false,
    duration: 16,
  },
  {
    key: 26,
    date: '30/04/2024',
    number_of_anomalies: 62,
    camera_id: 'CAM05-3',
    area: 'gymnasium',
    max_attendance: 1,
    warning: false,
    duration: 4,
  },
  {
    key: 27,
    date: '19/01/2024',
    number_of_anomalies: 84,
    camera_id: 'CAM02-2',
    area: 'library',
    max_attendance: 7,
    warning: false,
    duration: 7,
  },
  {
    key: 28,
    date: '25/11/2023',
    number_of_anomalies: 10,
    camera_id: 'CAM05-7',
    area: 'cafeteria',
    max_attendance: 4,
    warning: true,
    duration: 10,
  },
  {
    key: 29,
    date: '06/10/2023',
    number_of_anomalies: 52,
    camera_id: 'CAM01-4',
    area: 'library',
    max_attendance: 8,
    warning: false,
    duration: 6,
  },
  {
    key: 30,
    date: '09/11/2023',
    number_of_anomalies: 65,
    camera_id: 'CAM02-9',
    area: 'gymnasium',
    max_attendance: 7,
    warning: false,
    duration: 14,
  },
  {
    key: 31,
    date: '04/02/2024',
    number_of_anomalies: 63,
    camera_id: 'CAM10-1',
    area: 'gymnasium',
    max_attendance: 1,
    warning: false,
    duration: 17,
  },
  {
    key: 32,
    date: '14/10/2023',
    number_of_anomalies: 53,
    camera_id: 'CAM10-1',
    area: 'gymnasium',
    max_attendance: 2,
    warning: true,
    duration: 7,
  },
  {
    key: 33,
    date: '10/07/2024',
    number_of_anomalies: 3,
    camera_id: 'CAM06-1',
    area: 'gymnasium',
    max_attendance: 1,
    warning: true,
    duration: 18,
  },
  {
    key: 34,
    date: '30/05/2024',
    number_of_anomalies: 94,
    camera_id: 'CAM07-3',
    area: 'library',
    max_attendance: 8,
    warning: true,
    duration: 8,
  },
  {
    key: 35,
    date: '23/09/2024',
    number_of_anomalies: 75,
    camera_id: 'CAM10-8',
    area: 'gymnasium',
    max_attendance: 3,
    warning: true,
    duration: 18,
  },
  {
    key: 36,
    date: '05/01/2024',
    number_of_anomalies: 86,
    camera_id: 'CAM07-5',
    area: 'playground',
    max_attendance: 4,
    warning: true,
    duration: 15,
  },
  {
    key: 37,
    date: '28/09/2023',
    number_of_anomalies: 89,
    camera_id: 'CAM02-4',
    area: 'library',
    max_attendance: 3,
    warning: false,
    duration: 13,
  },
  {
    key: 38,
    date: '05/12/2023',
    number_of_anomalies: 60,
    camera_id: 'CAM10-2',
    area: 'playground',
    max_attendance: 2,
    warning: false,
    duration: 15,
  },
  {
    key: 39,
    date: '20/07/2024',
    number_of_anomalies: 60,
    camera_id: 'CAM10-5',
    area: 'library',
    max_attendance: 2,
    warning: false,
    duration: 4,
  },
  {
    key: 40,
    date: '29/10/2023',
    number_of_anomalies: 96,
    camera_id: 'CAM10-2',
    area: 'classroom',
    max_attendance: 2,
    warning: true,
    duration: 16,
  },
  {
    key: 41,
    date: '06/11/2023',
    number_of_anomalies: 79,
    camera_id: 'CAM04-9',
    area: 'playground',
    max_attendance: 2,
    warning: false,
    duration: 7,
  },
  {
    key: 42,
    date: '17/08/2024',
    number_of_anomalies: 21,
    camera_id: 'CAM05-6',
    area: 'playground',
    max_attendance: 3,
    warning: false,
    duration: 12,
  },
  {
    key: 43,
    date: '21/07/2024',
    number_of_anomalies: 43,
    camera_id: 'CAM10-7',
    area: 'playground',
    max_attendance: 6,
    warning: false,
    duration: 14,
  },
  {
    key: 44,
    date: '03/05/2024',
    number_of_anomalies: 27,
    camera_id: 'CAM10-3',
    area: 'classroom',
    max_attendance: 4,
    warning: false,
    duration: 9,
  },
  {
    key: 45,
    date: '31/03/2024',
    number_of_anomalies: 83,
    camera_id: 'CAM10-9',
    area: 'library',
    max_attendance: 6,
    warning: true,
    duration: 17,
  },
  {
    key: 46,
    date: '08/04/2024',
    number_of_anomalies: 52,
    camera_id: 'CAM03-6',
    area: 'playground',
    max_attendance: 7,
    warning: true,
    duration: 18,
  },
  {
    key: 47,
    date: '11/12/2023',
    number_of_anomalies: 78,
    camera_id: 'CAM07-3',
    area: 'library',
    max_attendance: 2,
    warning: false,
    duration: 13,
  },
  {
    key: 48,
    date: '22/06/2024',
    number_of_anomalies: 58,
    camera_id: 'CAM10-9',
    area: 'classroom',
    max_attendance: 8,
    warning: false,
    duration: 5,
  },
  {
    key: 49,
    date: '11/10/2023',
    number_of_anomalies: 100,
    camera_id: 'CAM10-1',
    area: 'classroom',
    max_attendance: 7,
    warning: false,
    duration: 19,
  }
]
